name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build e Testes Unitários
    runs-on: ubuntu-latest

    # onde o comando maven vai rodar mono repo
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x ./mvnw || true

      - name: Baixar dependências do Maven
        run: mvn dependency:go-offline

      - name: Executar Testes Unitários
        run: mvn test

      - name: Empacotar Aplicação (Build Final)
        run: mvn package -DskipTests